<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Try Catch</title>
  </head>
  <body></body>
  <script>
    /*const trataErro = (err) => {
      if (err.message === 'cep-error') {
        console.error('Erro no cep');
      } else {
        console.warn(err.message);
      }
    };

    try {
      //throw { tipo: 'frete-error', message: 'cep inexistente' };
      throw new Error('cep-error');
    } catch (err) {
      trataErro(err);
    }*/

    /*const getUsers = () => {
      return new Promise((reject, resolve) => {
        ///CÃ“DIGO....
        throw new Error('Erro invocado');
      });
    };

    getUsers().catch((err) => {
      console.log(err);
    });*/

    /*
    try {
      const x = 1;
      const y = x + z;
    } catch (err) {
      console.warn(err.name);
      console.log(err.message);
      console.error(err.stack);
    }*/

    /*
    try {
      //let cat g = "teste"
      eval('let cat g = "teste"');
    } catch (err) {
      console.warn(err.name);
      console.log(err.message);
      console.error(err.stack);
    }*/

    /*
    try {
      const num = 123;
      num.toUpperCase();
    } catch (err) {
      console.warn(err.name);
      console.log(err.message);
      console.error(err.stack);
    }*/

    /*
    try {
      function foo() {
        foo();
      }
      foo();
    } catch (err) {
      console.warn(err.name);
      console.log(err.message);
      console.error(err.stack);
    }*/
  </script>
</html>
